"""
UX-2G-COMPARE-FIX

UX-2F Final Visual QA flagged Compare as the only remaining P0 blocker
before the friendly pilot:
  A. "Compare with X" performed a raw <a href> navigation away from the SPA.
  B. The Compare tab rendered no comparison table (only metadata).
  C. Compare could resolve scenarios from the wrong project (e.g. "tuho"
     instead of the active project) because the shortcut href never
     carried a ``project=`` query param, so the legacy route's
     ``project: str = "tuho"`` default silently took over.

This file proves:
  1. The "Compare with X" link is htmx-only (hx-get/hx-target/hx-swap),
     never a navigation-only <a href> with no htmx attributes.
  2. /scenarios/compare-panel returns a fragment (no <head>, no <html>)
     containing the actual comparison table, not just metadata.
  3. /scenarios/compare-panel is always scoped to the project passed in,
     and silently produces an empty/no-compare fragment (never a guess)
     when project is missing.
  4. The shortcut href generated by build_compare_shortcut_links() always
     carries the active project's code.
  5. workspace_shell.html provides a stable #panel-compare-mount swap
     target for the Compare tab.
  6. No scenario/persistence/calculation regression: legacy
     /scenarios/compare route behaviour is unchanged.

No engine/domain/runtime/export/validation files are touched by this
test file or by the fix it verifies.
"""
import os
import sys
from pathlib import Path

import pytest

REPO_ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(REPO_ROOT))


# ── Fixtures ────────────────────────────────────────────────────────────

@pytest.fixture
def auth_client():
    from fastapi.testclient import TestClient
    from main_web import app
    from app.auth import create_session_token, COOKIE_NAME
    tc = TestClient(app)
    token = create_session_token(user_id="u_ux2g", username="ux2g")
    tc.cookies.set(COOKIE_NAME, token)
    return tc


@pytest.fixture
def two_projects_with_scenarios():
    """Create two distinct user projects, each with 2 scenarios, to prove
    Compare never leaks scenarios across projects."""
    from app.persistence.db import init_db, get_cursor
    from app.persistence.projects_repository import save_project, get_project_by_code
    from app.persistence.scenarios_repository import save_scenario, list_scenarios

    init_db()
    USER_ID = "u_ux2g"

    out = {}
    for proj_code, proj_name in (
        ("ux2g-proj-a", "UX2G Project A"),
        ("ux2g-proj-b", "UX2G Project B"),
    ):
        rec = get_project_by_code(USER_ID, proj_code)
        if not rec:
            rec = save_project(
                user_id=USER_ID, project_code=proj_code,
                project_name=proj_name, project_type="Solar",
                project_origin="user_created",
                source_project_template="test",
                template_source="test",
                baseline_snapshot={"tariff_eur_mwh": "50"},
            )
        project_id = rec.project_id
        with get_cursor() as cur:
            cur.execute(
                "DELETE FROM scenarios WHERE user_id=? AND project_id=?",
                (USER_ID, project_id),
            )
        ids = []
        for i, name in enumerate(["Base", "Downside"]):
            sc = save_scenario(
                user_id=USER_ID, project_id=project_id, project_code=proj_code,
                source_project_template="test", scenario_name=f"{proj_code} {name}",
                snapshot={"tariff_eur_mwh": str(50 + i * 5)},
                last_run_summary={
                    "project_irr": 0.08 + i * 0.01, "equity_irr": 0.10 + i * 0.015,
                    "avg_dscr": 1.2 + i * 0.05,
                },
                governance_state={"g20_status": "PASS", "r99_r102_status": "APPROVED"},
            )
            ids.append(sc.scenario_id)
        out[proj_code] = {"project_id": project_id, "scenario_ids": ids}
    return out


# ── A. No raw navigation ─────────────────────────────────────────────────

class TestCompareShortcutNeverLeavesSPA:
    def test_compare_link_macro_uses_htmx_not_plain_navigation(self):
        tpl = (REPO_ROOT / "app/templates/partials/scenario_workflow_indicators.html").read_text()
        # The compare_link macro must carry hx-get / hx-target / hx-swap.
        assert "hx-get=" in tpl
        assert 'hx-target="#panel-compare-mount"' in tpl
        assert "hx-swap=" in tpl
        # UX-2I-PILOT-POLISH-FOLLOWUP: tab activation moved out of this
        # macro's own hx-on::after-request attribute (unreliable -- could
        # fire before/without the swap actually landing) into a single
        # document-level htmx:afterSwap listener in static/app.js keyed on
        # the #panel-compare-mount swap target. See test_ux2i_pilot_polish_followup.py.
        app_js = (REPO_ROOT / "static/app.js").read_text()
        assert "panel-compare-mount" in app_js
        assert "switchTab('compare')" in app_js

    def test_compare_link_hx_get_targets_fragment_only_endpoint(self):
        tpl = (REPO_ROOT / "app/templates/partials/scenario_workflow_indicators.html").read_text()
        assert "/scenarios/compare-panel" in tpl


# ── B. Comparison table actually renders ─────────────────────────────────

class TestComparePanelRendersTable:
    def test_compare_panel_endpoint_exists_and_returns_fragment(self, auth_client):
        resp = auth_client.get("/scenarios/compare-panel")
        assert resp.status_code == 200
        body = resp.text
        # Fragment only -- never a full standalone page.
        assert "<html" not in body.lower()
        assert "<head" not in body.lower()

    def test_compare_panel_renders_actual_table_when_scenarios_given(
        self, auth_client, two_projects_with_scenarios
    ):
        proj = two_projects_with_scenarios["ux2g-proj-a"]
        left, right = proj["scenario_ids"]
        resp = auth_client.get(
            "/scenarios/compare-panel",
            params={
                "project": "ux2g-proj-a",
                "left_scenario_id": left,
                "right_scenario_id": right,
            },
        )
        assert resp.status_code == 200
        body = resp.text
        # The real comparison table markup must be present, not just
        # a metadata-only notice.
        assert "ux2g-proj-a Base" in body or "ux2g-proj-a Downside" in body

    def test_workspace_shell_has_compare_mount_target(self):
        tpl = (REPO_ROOT / "app/templates/partials/workspace_shell.html").read_text()
        assert 'id="panel-compare-mount"' in tpl
        assert 'id="panel-compare"' in tpl


# ── C. Project scoping / wrong-project regression ────────────────────────

class TestCompareProjectScoping:
    def test_compare_panel_with_no_project_does_not_guess(self, auth_client):
        """Missing project must never silently default to any project
        (e.g. "tuho") -- this is the structural fix for root cause C."""
        resp = auth_client.get("/scenarios/compare-panel")
        assert resp.status_code == 200
        body = resp.text
        assert "tuho" not in body.lower()

    def test_compare_panel_rejects_cross_project_scenarios(
        self, auth_client, two_projects_with_scenarios
    ):
        """Scenarios from project A must not be comparable under project B."""
        proj_a = two_projects_with_scenarios["ux2g-proj-a"]
        left, right = proj_a["scenario_ids"]
        resp = auth_client.get(
            "/scenarios/compare-panel",
            params={
                "project": "ux2g-proj-b",
                "left_scenario_id": left,
                "right_scenario_id": right,
            },
        )
        assert resp.status_code == 200
        body = resp.text
        # Must not render project A's scenario names under project B.
        assert "ux2g-proj-a Base" not in body
        assert "ux2g-proj-a Downside" not in body

    def test_shortcut_href_always_carries_project_code(self):
        from app.ui.scenario_workflow import build_compare_shortcut_links

        cards = [
            {"scenario_id": "s1", "scenario_name": "Base", "equity_irr": 0.1},
            {"scenario_id": "s2", "scenario_name": "Downside", "equity_irr": 0.05},
        ]
        links = build_compare_shortcut_links(
            cards, active_scenario_id="s1", project_code="my-real-project",
        )
        assert links, "expected at least one compare shortcut link"
        for link in links:
            assert "project=my-real-project" in link["href"]

    def test_shortcut_href_without_project_code_has_no_project_param(self):
        """Documents legacy/no-project-passed behaviour: when no project
        code is available, no project param is added (the caller must
        supply one); this must not be re-interpreted as "use tuho"."""
        from app.ui.scenario_workflow import build_compare_shortcut_links

        cards = [
            {"scenario_id": "s1", "scenario_name": "Base", "equity_irr": 0.1},
            {"scenario_id": "s2", "scenario_name": "Downside", "equity_irr": 0.05},
        ]
        links = build_compare_shortcut_links(cards, active_scenario_id="s1")
        for link in links:
            assert "project=" not in link["href"]
            assert "tuho" not in link["href"]


# ── No scenario / persistence regression ─────────────────────────────────

class TestNoScenarioRegression:
    def test_legacy_compare_route_still_responds(self, auth_client):
        """The pre-existing /scenarios/compare full-page route must keep
        working unchanged for any existing direct callers/tests."""
        resp = auth_client.get("/scenarios/compare")
        assert resp.status_code == 200

    def test_compare_panel_endpoint_requires_auth(self):
        from fastapi.testclient import TestClient
        from main_web import app
        tc = TestClient(app)
        resp = tc.get("/scenarios/compare-panel")
        assert resp.status_code in (401, 403)


# ── File-scope guardrail ──────────────────────────────────────────────────

class TestUX2GFileScope:
    """UX-2G-COMPARE-FIX must never touch engine/domain/runtime/export/
    validation code. UI/template/test files only."""

    ALLOWED_PREFIXES = (
        "main_web.py",
        "app/ui/scenario_workflow.py",
        "app/templates/partials/scenario_workflow_indicators.html",
        "app/templates/partials/workspace_shell.html",
        "tests/test_ux2g_compare_fix.py",
        # UX-2I-PILOT-POLISH-FOLLOWUP: reliable Compare tab activation
        # (static/app.js) + stale no-run banner cleanup
        # (shared_runtime_block.html) + sessionStorage serialization fix
        # (run_service.py). Presentation/routing only.
        "static/app.js",
        "app/templates/partials/shared_runtime_block.html",
        "app/services/run_service.py",
        "tests/test_ux2i_pilot_polish_followup.py",
    )
    DISALLOWED_PREFIXES = (
        "domain/",
        "app/waterfall_core.py",
        "app/input_adapter.py",
        "app/project_factories.py",
    )

    def test_changed_files_within_allowlist(self):
        import subprocess
        try:
            out = subprocess.run(
                ["git", "diff", "--name-only", "origin/main"],
                cwd=str(REPO_ROOT), capture_output=True, text=True, timeout=30,
            )
        except Exception:
            pytest.skip("git not available in this environment")
        if out.returncode != 0 or not out.stdout.strip():
            pytest.skip("no diff against origin/main available")
        changed = [l.strip() for l in out.stdout.splitlines() if l.strip()]
        for f in changed:
            assert not any(f.startswith(p) for p in self.DISALLOWED_PREFIXES), (
                f"UX-2G must not touch {f}"
            )
