"""
finco_parity.generate_tax_cfads_corrections — Generate the Phase 2B corrections ledger.

Runs the TAX_CFADS_V1 comparison for all baselines, records each difference as an
APPROVED_FINANCIAL_CORRECTION in finco_parity/corrections/tax_cfads_v1_exact.json.

Usage::

    python -m finco_parity.generate_tax_cfads_corrections

Regenerate whenever the candidate implementation intentionally changes values.
After regenerating, commit the updated corrections file so the CI can verify
that future candidate runs match the approved ledger exactly.

The ledger format is a per-field, per-baseline, per-period record:
  {
    "baseline_id": "oborovo",
    "field_path": "tax_and_cfads.taxable_profit_keur[3]",
    "baseline_value": -40.97,
    "candidate_value": 217.38,
    "delta": 258.35,
    "reason": "Rate change hr_reduced_factory_v1 (10%) vs legacy (18%); calendar year axis",
    "status": "APPROVED_FINANCIAL_CORRECTION"
  }

Import boundary
---------------
This module may only import from:
  - Python standard library
  - finco_parity.*
  - financial_engine.*  (deferred via candidate provider)
"""
from __future__ import annotations

import json
import sys
from pathlib import Path

CORRECTIONS_PATH = Path(__file__).parent / "corrections" / "tax_cfads_v1_exact.json"

_ALL_BASELINE_IDS = ("tuho", "oborovo", "generic_solar", "generic_wind")

_BASELINE_REASONS: dict[str, str] = {
    "tuho": (
        "Phase 2B uses hr_standard_factory_v1 (18%, same rate as legacy) but introduces "
        "calendar-year tax axis (Dec31 splitting), TAX_YEAR_LAST_PERIOD cash timing, "
        "opening loss vintage 25 000 kEUR (origin 2028), and canonical CFADS computation. "
        "Legacy engine uses per-period taxable income with year_index grouping."
    ),
    "oborovo": (
        "Phase 2B uses hr_reduced_factory_v1 (10%) vs legacy (~18% assumed); "
        "introduces calendar-year tax axis, TAX_YEAR_LAST_PERIOD cash timing, "
        "and canonical CFADS computation."
    ),
    "generic_solar": (
        "Phase 2B uses de_demo_factory_v1 (25% factory assumption) vs legacy; "
        "introduces calendar-year tax axis, TAX_YEAR_LAST_PERIOD cash timing, "
        "and canonical CFADS computation."
    ),
    "generic_wind": (
        "Phase 2B uses de_demo_factory_v1 (25% factory assumption) vs legacy; "
        "introduces calendar-year tax axis, TAX_YEAR_LAST_PERIOD cash timing, "
        "and canonical CFADS computation."
    ),
}


def generate_corrections() -> dict:
    """Run TAX_CFADS_V1 comparison for all baselines, collect per-field diffs."""
    from finco_parity.financial_engine_tax_cfads_candidate import (
        generate_tax_cfads_candidate_snapshot,
    )
    from finco_parity.manifest import SNAPSHOTS_DIR
    from finco_parity.profiles import ComparisonProfile, project_for_profile
    from finco_parity.comparison import compare_snapshots

    profile = ComparisonProfile.TAX_CFADS_V1
    records: list[dict] = []
    summary: dict[str, dict] = {}

    for baseline_id in _ALL_BASELINE_IDS:
        print(f"  [{baseline_id}] generating candidate ...", flush=True)
        snapshot_path = SNAPSHOTS_DIR / f"{baseline_id}.json"
        with open(snapshot_path) as f:
            baseline_snap = json.load(f)

        candidate_snap = generate_tax_cfads_candidate_snapshot(baseline_id)
        baseline_proj = project_for_profile(baseline_snap, profile)
        candidate_proj = project_for_profile(candidate_snap, profile)

        cmp = compare_snapshots(baseline_proj, candidate_proj, baseline_id)
        diffs = cmp.differences

        reason = _BASELINE_REASONS.get(baseline_id, "Phase 2B approved financial correction")
        for d in diffs:
            records.append({
                "baseline_id": baseline_id,
                "field_path": d.path,
                "baseline_value": d.baseline_value,
                "candidate_value": d.current_value,
                "delta": (
                    (d.current_value - d.baseline_value)
                    if isinstance(d.baseline_value, (int, float))
                    and isinstance(d.current_value, (int, float))
                    else None
                ),
                "reason": reason,
                "status": "APPROVED_FINANCIAL_CORRECTION",
            })

        n_identical = len(cmp.differences) == 0
        summary[baseline_id] = {
            "status": "IDENTICAL" if n_identical else "APPROVED_FINANCIAL_CORRECTION",
            "n_approved_corrections": len(diffs),
        }
        print(f"  [{baseline_id}] {len(diffs)} approved corrections", flush=True)

    return {
        "schema": "tax_cfads_exact_corrections/1.0",
        "profile": "TAX_CFADS_V1",
        "description": (
            "Per-field, per-baseline, per-period approved corrections for Phase 2B "
            "TAX_CFADS_V1 parity. Generated by generate_tax_cfads_corrections.py. "
            "Commit this file after intentional engine changes. "
            "Differences matching this ledger → APPROVED_FINANCIAL_CORRECTION. "
            "Differences NOT matching → UNEXPLAINED_DRIFT (exit non-zero)."
        ),
        "summary": summary,
        "corrections": records,
    }


def main() -> int:
    print("Generating TAX_CFADS_V1 exact corrections ledger ...", flush=True)
    ledger = generate_corrections()
    CORRECTIONS_PATH.parent.mkdir(parents=True, exist_ok=True)
    CORRECTIONS_PATH.write_text(json.dumps(ledger, indent=2, ensure_ascii=False) + "\n")
    n = len(ledger["corrections"])
    print(f"Written {n} correction records to {CORRECTIONS_PATH}", flush=True)
    return 0


if __name__ == "__main__":
    sys.exit(main())
