"""finco_parity.tax_reference_inputs — Explicit per-baseline tax reference registry.

This module is the parity-layer source of truth for:
  * Per-baseline TaxPolicy (constructed from canonical project inputs).
  * Opening loss vintage positions.

It does NOT live inside financial_engine.  The financial_engine accepts an
explicit TaxPolicy and explicit opening vintages; project identity is resolved
HERE, in the parity adapter layer.

TUHO opening-loss: RESOLVED — ZERO (no pre-model vintages)
------------------------------------------------------------
Source: manual TUHO Excel workbook inspection (20260330_TUHO_BP_2.xlsm)

DS sheet (first modeled period):
  SHL Beginning    = 29,135 kEUR
  SHL PIK Interest =  3,569 kEUR
  SHL Ending       = 32,704 kEUR  (29,135 + 3,569 = 32,704 ✓)

P&L sheet (first modeled period):
  SHL Interest expense    = 3,569 kEUR
  Financial Earnings      = −3,569 kEUR
  EBT                     = −3,569 kEUR
  Fiscal Reintegration    = 0          (SHL interest currently deductible — EXCEL POLICY)
  Taxable Income          = −3,569 kEUR
  Losses N-1 (first period) = 0 / blank  (no pre-model carryforward)
  Losses N (first period)   = −3,569 kEUR (generated inside first period)
  Following period Losses N-1 = −3,569 kEUR (carried forward from first period)

Conclusions:
  1. SHL interest is simultaneously PIK'd into SHL liability AND expensed through P&L.
  2. No pre-model tax loss exists — opening LCF = ZERO.
  3. The 3,569 kEUR loss is generated by the model's first-period computation
     (SHL interest → P&L → taxable income). It is NOT an opening input.
  4. Prior factory value of 25,000 kEUR is unsupported as clean-engine source truth;
     retained unchanged in the legacy factory for compatibility and explicitly excluded
     from clean-engine tax source resolution.
  5. 3,569 kEUR must NOT be encoded as a historical/pre-construction opening vintage.

``build_opening_loss_vintages("tuho")`` returns an empty tuple ().

For baselines with no opening losses, an explicit reviewed-zero position is
recorded rather than relying on an absent tuple.
"""
from __future__ import annotations

from dataclasses import dataclass
from typing import Any, Optional


# ---------------------------------------------------------------------------
# Construction-generated carryforward at the operation boundary
# ---------------------------------------------------------------------------

@dataclass(frozen=True)
class ConstructionGeneratedVintage:
    """A tax loss carryforward generated during the construction period,
    supplied at the operation boundary.

    DISTINCT from OpeningTaxLossVintageInput (historical pre-construction losses).
    For TUHO: historical opening LCF = ZERO. This vintage represents losses
    generated during construction (SHL interest expensed through P&L,
    Fiscal Reintegration=0).

    The Phase 2B clean engine boundary does not represent the full 18-month
    source construction interval (2028-06-30 -> 2029-12-30) — it uses a 6-month
    proxy period (2029-07-01 to 2030-01-01). Therefore the construction-generated
    LCF is supplied at the operation boundary rather than computed through the
    period engine.

    origin_year=2029 is a MODEL_BOUNDARY_CONVENTION: the full workbook-observed
    construction-generated carryforward is assigned to the terminal year of the
    source construction/model period. No authoritative 2028-vs-2029 tax-year split
    has been extracted from the workbook. TUHO economics are unaffected by any
    possible expiry-year distinction because the loss is fully utilized before
    either possible expiry boundary (2033 or 2034).
    """
    amount_keur: float
    origin_label: str
    origin_year: int
    source_doc: str
    source_cells: str
    evidence_type: str
    workbook_sha: str


def build_construction_generated_carryforward_at_cod(baseline_id: str) -> tuple:
    """Return construction-generated LCF vintages at the operation boundary.

    DISTINCT from historical opening LCF (which is zero for TUHO).
    Source: construction-period SHL interest expensed through P&L with
    Fiscal Reintegration=0 -> tax loss generated during construction.

    The Phase 2B clean engine boundary uses a 6-month proxy construction period
    (2029-07-01 to 2030-01-01) rather than the full 18-month source construction
    interval (2028-06-30 -> 2029-12-30).  Mapping the 18-month IDC into the
    6-month proxy period is incorrect.  Instead the construction-generated LCF
    is supplied at the operation boundary via
    CONSTRUCTION_GENERATED_CARRYFORWARD_AT_OPERATION_BOUNDARY.

    origin_year=2029 is a MODEL_BOUNDARY_CONVENTION: the full workbook-observed
    construction-generated carryforward is assigned to the terminal year of the
    source construction/model period (2029-12-30).  No authoritative 2028-vs-2029
    tax-year split has been extracted.  TUHO economics are unaffected by the
    possible expiry-year distinction because the loss is fully utilized before
    either possible expiry boundary.

    Source: 20260330_TUHO_BP_2.xlsm (manual review,
    workbook_sha=UNAVAILABLE_NOT_CAPTURED).
    Evidence cells: DS G121-G126, P&L G27-G36.

    Raises
    ------
    RuntimeError
        If the registered construction fixture is missing or has invalid data
        (GOVERNANCE FAILURE — hard fail, never silently ignored).
    """
    if baseline_id == "tuho":
        import json
        import os
        fixture_path = "tests/fixtures/construction_parity/tuho_construction_snapshot.json"
        if not os.path.exists(fixture_path):
            raise RuntimeError(
                f"GOVERNANCE FAILURE: Registered TUHO construction fixture not found: "
                f"{fixture_path}"
            )
        with open(fixture_path) as f:
            snap = json.load(f)
        total_idc = snap.get("totals_keur", {}).get("total_shl_idc")
        if total_idc is None or total_idc <= 0:
            raise RuntimeError(
                f"GOVERNANCE FAILURE: TUHO construction snapshot missing or invalid "
                f"total_shl_idc: {total_idc}"
            )
        return (ConstructionGeneratedVintage(
            amount_keur=float(total_idc),
            origin_label="CONSTRUCTION_GENERATED",
            origin_year=2029,
            source_doc="20260330_TUHO_BP_2.xlsm",
            source_cells="DS G121-G126, P&L G27-G36",
            evidence_type="MANUAL_WORKBOOK_REVIEW",
            workbook_sha="UNAVAILABLE_NOT_CAPTURED",
        ),)
    return ()


class TuhoOpeningLossVintageUnresolved(RuntimeError):
    """Raised when TUHO opening-loss vintage cannot be resolved from a primary source.

    RESOLVED: manual workbook inspection confirmed zero pre-model opening LCF.
    This exception is retained for backwards compatibility with any callers that
    guard against it, but build_opening_loss_vintages("tuho") no longer raises it.
    """


# ---------------------------------------------------------------------------
# Registry schema
# ---------------------------------------------------------------------------

_OPENING_LOSS_REGISTRY: dict[str, list[dict[str, Any]]] = {
    "tuho": [
        {
            # RESOLVED ZERO — manual workbook inspection (20260330_TUHO_BP_2.xlsm)
            # DS sheet: SHL Beginning=29,135, PIK=3,569, SHL Ending=32,704 (first period)
            # P&L: Losses N-1 (first period) = 0 / blank — no pre-model carryforward.
            # The 3,569 kEUR loss is generated inside the model's first-period
            # taxable-income computation. It is NOT an opening vintage.
            "vintage_id": None,   # reviewed zero — no opening loss
            # Source: Manual workbook review — 20260330_TUHO_BP_2.xlsm
            # workbook_sha: UNAVAILABLE / NOT_CAPTURED
            # Evidence type: MANUAL_WORKBOOK_REVIEW
            #
            # DS sheet (verified cells: G121/G122/G125/G126 area):
            #   SHL Beginning = 29,135 kEUR
            #   SHL Net Interest (PIK) = 3,569 kEUR
            #   SHL Interests to Capitalize = 3,569 kEUR
            #   SHL Ending = 32,704 kEUR (= 29,135 + 3,569)
            #
            # P&L sheet (first modeled period, verified cells: G27-G36):
            #   G27 Shareholder Loan Interests = 3,569 kEUR (expense)
            #   G30 Financial Earnings = -3,569 kEUR
            #   G32 Earnings Before Tax = -3,569 kEUR
            #   G34 Fiscal Reintegration = 0  [currently deductible — EXCEL POLICY]
            #   G35 Taxable Income = -3,569 kEUR
            #   G36 Losses N-1 (first period) = 0  [NO pre-model opening loss]
            #   H36 Losses N-1 (following period) = -3,569 [first-period loss carried forward]
            #
            # Conclusion:
            #   - Historical/pre-construction opening LCF = ZERO
            #   - The 3,569 kEUR loss is GENERATED by construction-period SHL interest
            #     flowing through P&L (not an opening input)
            #   - The factory value prior_tax_loss_keur=25_000 is legacy compatibility
            #     debt — retained unchanged; it is NOT used by the clean-engine candidate
            "source_field": "manual_workbook_review.20260330_TUHO_BP_2.xlsm.PL_G36",
            "amount_keur": 0.0,
            "origin_tax_year": None,
            "source_rationale": (
                "Reviewed zero: manual TUHO Excel workbook inspection "
                "(20260330_TUHO_BP_2.xlsm). "
                "P&L G36 Losses N-1 (first period) = 0 — no pre-model LCF. "
                "3,569 kEUR construction-period SHL interest flows through P&L "
                "(G27->G30->G32->G35), Fiscal Reintegration=0 (deductible). "
                "Loss is generated inside the model, not an opening input. "
                "factory prior_tax_loss_keur=25_000 is legacy-engine compatibility only."
            ),
            "policy_id": "hr_standard_factory_v1",
        }
    ],
    "oborovo": [
        {
            "vintage_id": None,  # reviewed zero position — no opening loss
            "source_field": "project_inputs.tax.prior_tax_loss_keur",
            "amount_keur": 0.0,
            "origin_tax_year": None,
            "source_rationale": (
                "Reviewed zero: create_default_oborovo().tax.prior_tax_loss_keur == 0.0"
            ),
            "policy_id": "hr_reduced_factory_v1",
        }
    ],
    "generic_solar": [
        {
            "vintage_id": None,
            "source_field": "project_inputs.tax.prior_tax_loss_keur",
            "amount_keur": 0.0,
            "origin_tax_year": None,
            "source_rationale": (
                "Reviewed zero: create_default_solar_project().tax.prior_tax_loss_keur == 0.0"
            ),
            "policy_id": "de_demo_factory_v1",
        }
    ],
    "generic_wind": [
        {
            "vintage_id": None,
            "source_field": "project_inputs.tax.prior_tax_loss_keur",
            "amount_keur": 0.0,
            "origin_tax_year": None,
            "source_rationale": (
                "Reviewed zero: create_default_wind_project().tax.prior_tax_loss_keur == 0.0"
            ),
            "policy_id": "de_demo_factory_v1",
        }
    ],
}

# ---------------------------------------------------------------------------
# Per-baseline policy parameters derived from canonical project inputs.
# Policy IDs encode country and designation — NOT project names or codes.
# ---------------------------------------------------------------------------

_POLICY_PARAMS: dict[str, dict[str, Any]] = {
    "tuho": {
        "policy_id": "hr_standard_factory_v1",
        "policy_version": "1.0",
        # Source: create_default_tuho_wind1().tax  (country HR, rate 18%)
        "corporate_rate": 0.18,
        "periods_per_tax_year": 2,
        "loss_carryforward_years": 5,
        "atad_enabled": True,
        "atad_ebitda_limit": 0.30,
        "atad_de_minimis_threshold_keur_annual": 3_000.0,
        "cash_tax_timing": "tax_year_last_period",
        "cash_tax_payment_lag_periods": 0,
    },
    "oborovo": {
        "policy_id": "hr_reduced_factory_v1",
        "policy_version": "1.0",
        # Source: create_default_oborovo().tax  (country HR, rate 10%)
        "corporate_rate": 0.10,
        "periods_per_tax_year": 2,
        "loss_carryforward_years": 5,
        "atad_enabled": True,
        "atad_ebitda_limit": 0.30,
        "atad_de_minimis_threshold_keur_annual": 3_000.0,
        "cash_tax_timing": "tax_year_last_period",
        "cash_tax_payment_lag_periods": 0,
    },
    "generic_solar": {
        "policy_id": "de_demo_factory_v1",
        "policy_version": "1.0",
        # Source: create_default_solar_project().tax  (country DE, rate 25%)
        # NOTE: 25% is the explicit model/factory assumption, NOT a verified
        # German legal tax rate.  German CIT + solidarity surcharge is ~15.83%
        # at the federal level before trade tax.  The factory uses 25% as a
        # rounded demonstration rate.
        "corporate_rate": 0.25,
        "periods_per_tax_year": 2,
        "loss_carryforward_years": 5,
        "atad_enabled": True,
        "atad_ebitda_limit": 0.30,
        "atad_de_minimis_threshold_keur_annual": 3_000.0,
        "cash_tax_timing": "tax_year_last_period",
        "cash_tax_payment_lag_periods": 0,
    },
    "generic_wind": {
        "policy_id": "de_demo_factory_v1",
        "policy_version": "1.0",
        # Source: create_default_wind_project().tax  (country DE, rate 25%)
        # NOTE: 25% is the explicit model/factory assumption.  See generic_solar.
        "corporate_rate": 0.25,
        "periods_per_tax_year": 2,
        "loss_carryforward_years": 5,
        "atad_enabled": True,
        "atad_ebitda_limit": 0.30,
        "atad_de_minimis_threshold_keur_annual": 3_000.0,
        "cash_tax_timing": "tax_year_last_period",
        "cash_tax_payment_lag_periods": 0,
    },
}


def build_tax_policy(baseline_id: str):
    """Build a TaxPolicy for the given baseline from canonical project inputs.

    Parameters
    ----------
    baseline_id:
        One of ``tuho``, ``oborovo``, ``generic_solar``, ``generic_wind``.

    Returns
    -------
    TaxPolicy (frozen dataclass from financial_engine.policies.tax).
    """
    if baseline_id not in _POLICY_PARAMS:
        raise ValueError(
            f"No policy registered for baseline_id {baseline_id!r}. "
            f"Valid: {sorted(_POLICY_PARAMS)}"
        )
    from financial_engine.policies.tax import TaxPolicy, CashTaxTiming

    p = _POLICY_PARAMS[baseline_id]
    return TaxPolicy(
        policy_id=p["policy_id"],
        policy_version=p["policy_version"],
        corporate_rate=p["corporate_rate"],
        periods_per_tax_year=p["periods_per_tax_year"],
        loss_carryforward_years=p["loss_carryforward_years"],
        atad_enabled=p["atad_enabled"],
        atad_ebitda_limit=p["atad_ebitda_limit"],
        atad_de_minimis_threshold_keur_annual=p["atad_de_minimis_threshold_keur_annual"],
        cash_tax_timing=CashTaxTiming(p["cash_tax_timing"]),
        cash_tax_payment_lag_periods=p["cash_tax_payment_lag_periods"],
    )


def build_opening_loss_vintages(baseline_id: str) -> tuple:
    """Build the opening loss vintage tuple for the given baseline.

    Returns an empty tuple for baselines with reviewed-zero opening-loss positions
    (including TUHO, which has zero pre-model tax-loss carryforward per manual
    workbook inspection of 20260330_TUHO_BP_2.xlsm).
    """
    if baseline_id not in _OPENING_LOSS_REGISTRY:
        raise ValueError(
            f"No opening loss registry entry for {baseline_id!r}. "
            f"Valid: {sorted(_OPENING_LOSS_REGISTRY)}"
        )

    from financial_engine.inputs import OpeningTaxLossVintageInput

    vintages = []
    for entry in _OPENING_LOSS_REGISTRY[baseline_id]:
        amount = entry["amount_keur"]
        if amount <= 0.0 or entry["origin_tax_year"] is None:
            # Reviewed zero — no vintage to create.
            continue
        vintages.append(OpeningTaxLossVintageInput(
            origin_tax_year=entry["origin_tax_year"],
            amount_keur=amount,
            source_label=entry.get("source_rationale", "")[:120],
        ))
    return tuple(vintages)


def get_policy_summary() -> dict[str, dict[str, Any]]:
    """Return a human-readable summary of all registered policies."""
    return {
        bid: {
            "policy_id": p["policy_id"],
            "corporate_rate": p["corporate_rate"],
            "loss_carryforward_years": p["loss_carryforward_years"],
            "atad_enabled": p["atad_enabled"],
            "atad_ebitda_limit": p["atad_ebitda_limit"],
            "atad_de_minimis_threshold_keur_annual": p["atad_de_minimis_threshold_keur_annual"],
        }
        for bid, p in _POLICY_PARAMS.items()
    }


def get_opening_loss_summary() -> dict[str, list[dict[str, Any]]]:
    """Return the full opening loss registry for audit purposes."""
    return {
        bid: [dict(entry) for entry in entries]
        for bid, entries in _OPENING_LOSS_REGISTRY.items()
    }
